### DISCUSSION TITLE
Is there a way to deploy to cloudflare pages

### DISCUSSION THREAD

**Discussion by ooexiaoo** [oleeskild/obsidian-digital-garden#530] [Q&A]
Hi, I've been using the plugin to deploy my site to vercel and netlify, but would like to know of its possible to deploy to cloudflare pages somehow.

The documentation says its possible, but there are no clear directions. I tried the normal way to deploy from cloudflare pages by logging into cloudflare, connecting it to GitHub and selecting my repo, but it doesn't work.

The site just shows an error, when I try to visit the cloudflare link i.e "sitename.pages.dev"

**Comment by chrishutchison9** [comment]
It's absolutely possible. I'm doing it now. Here's my workflow. You will have to change a couple of things and refer to [Use Direct Upload with continuous integration · Cloudflare Pages docs](https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/)

Sorry I don't have a better put-together guide as of yet.

```
on:
  push:
    branches:
      - chris-changes
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build
          
        ##
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: [replace-with-your-account-id]
          projectName: digital-garden
          directory: dist
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: chris-changes
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'
```
