### ISSUE TITLE
Overcoming Vercel daily 100 deployment limit

### ISSUE THREAD

**Issue by ransurf** [oleeskild/obsidian-digital-garden#320]
*I still have yet to run it once, will leave another comment once I do*

I just wanted to share a workaround I'm trying out using GitHub Actions to prevent auto-deployment until midnight at the end of each day since the one commit per file workflow has led me to go over the limit once.

I created a new "master" branch that I set as the deployment branch in Vercel settings, and then disabled auto-deployment with the following configuration:

`vercel.json`
```js
{
    "git": {
      "deploymentEnabled": {
        "main": false
      }
    },
    "outputDirectory": "dist",
    "installCommand": "npm install",
    "buildCommand": "npm run build",
    "devCommand": "npm run start",
    "routes": [
        { "handle": "filesystem" },
        { "src": "/(.*)", "status": 404, "dest": "/404" }
      ]
}
```

Here is the github workflows script I'm using as well.

`.github/workflows/auto_merge.yml`
```
name: 'Daily auto-merge'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Merge and push
        run: |
          git fetch origin master:master
          git checkout master
          git merge main --no-ff -m "Merge main to master"
          git push origin master

```
