### ISSUE TITLE
How do I see all frontmatter on my website?

### ISSUE THREAD

**Issue by DudeThatsErin** [oleeskild/obsidian-digital-garden#354]
This is an example of the frontmatter I have in a file:
```yaml
---
dg-publish: true
aliases:
 - basic
 - pen
 - paper
tags: 
 - basic notes
 - non-digital notes
apps: 
 - android
 - iOS
 - macOS
 - windows
 - linux
 - web
openSource: ✅
worksOffline: ✅
doDates: ✅
dueDates: ✅
attachmentSupport: ✅
hasAnAPI: ❌
reminders: ❌
locationBasedReminders: ✅
nlp: ✅
kanbanView: ✅
listView: ✅
switchBetween: ✅
hq: "Your House"
Price URL:
is there a free option: ✅
one time payment option: ❌
---
```
Is there a way to display all of this information online at the top of a file?

I plan to use dataview on a few pages to compare things. Trying to do something similar to this: https://dudethatserin.notion.site/Welcome-to-Erin-s-Tool-Wiki-11f1e3d1d62a4b40ae2c0925c0bf5670?pvs=4

Is there a way to do this with the digital garden?
