### ISSUE TITLE
Request: Compatibility with this CSS snippe group

### ISSUE THREAD

**Issue by oyes77** [oleeskild/obsidian-digital-garden#360]
https://github.com/efemkay/obsidian-modular-css-layout

This would allow lots of flexibility and more customization in the digital garden.

**Comment by SemanticBeeng** [comment]
+1 and w.r.t. modularity, it would be great to unify how `embeds` / `transclusions` are formatted.

This formatting is an issue in `Obsidian` client and also publishing.

As shown in https://github.com/oleeskild/obsidian-digital-garden/issues/361, even through embeds render correctly in Obsidian client they render with some form of padding around that breaks the parent page.

See themes that do fix the formatting of embeds 
* `AnuPpucin` (https://github.com/AnubisNekhet/AnuPpuccin#simplified-markdown-embeds) and 
* `ebullientworks` (https://github.com/ebullient/obsidian-theme-ebullientworks#style-settings)

But the solutions are partial, different (non canonical) and non modular.

Is there a way to introduce a canonical (uniform, shared between plugins), modular approach that works in both client and at publishing?

/cc @uroybd

**Comment by danielo515** [comment]
I was about opening an issue about this, but glad to see there is already awareness.
Could it be possible to just include those CSS files as part of the eleventhly build? Or it will not be enough?

**Comment by danielo515** [comment]
I think I found a suitable workaround for this. You need to add some custom css for it to work:
You just copy this code under a css file at `src/site/styles/user` for example `src/site/styles/user/multi-column.css`

```css
.callout[data-callout='multi-column']>.callout-content {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(112px, 1fr));
    grid-gap: .5rem;
}
.callout[data-callout='multi-column'] {
    padding: 0 1rem;
    margin: 0;
}
.callout[data-callout='multi-column']>.callout-content > p
 {
    display: none;
}
.callout[data-callout='multi-column']>.callout-title {
    display: none;
}
```
It will look like this 
<img width="870" alt="image" src="https://github.com/oleeskild/obsidian-digital-garden/assets/2270425/87281de7-82cc-4595-9c51-9b1edf5cd2f9">
