### ISSUE TITLE
Link aliases in YAML

### ISSUE THREAD

**Issue by davidkopp** [oleeskild/obsidian-digital-garden#537]
With the new Obsidian Properties feature it is now quite common to use links to notes in the YAML frontmatter. Also link aliases are supported. The following YAML is valid within Obsidian:

```yaml
dg-publish: true
links:
  - "[[Link to Note|Link Alias]]"
```

However, this leads to the following error raised by Eleventy:

Error:
```log
Original error stack trace: YAMLException: unknown escape sequence at line 11, column 71:
[11ty]      ... Link to Note\|Link Alias]]"
```
