### ISSUE TITLE
Publication center diff performs transclusion replacements in code blocks

### ISSUE THREAD

**Issue by tsnieman** [oleeskild/obsidian-digital-garden#599]
If a code block contains Obsidian transclusion syntax, the publication center will show a diff that contains the full transclusion.

For example, assume you have a note ``embeds.md``` and then write a codeblock in a publishable note like this:
```css
/* Increase <br> in ![[embeds]] */
.internal-embed br {
    margin: 1em 0;
    display: block;
    content: "";
}
```

While I believe #596 likely prevents actual transclusion upon publishing, it doesn't seem to have an effect on the diff produced in the publication center.

Related:
- #595
- #596
